# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IzeDev < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "0.0.0-dev"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kobrikx/test/releases/download/0.0.0-dev/ize-dev_0.0.0-dev_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "64ace35b41db014ab22d30acdfe993e245a6f022292dde8ef61602c5976fa70e"

      def install
        bin.install "ize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kobrikx/test/releases/download/0.0.0-dev/ize-dev_0.0.0-dev_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6f82207c304c8bc199f565572c32704614ceb5cec3fcb3ef70da4e7c6275f899"

      def install
        bin.install "ize"
      end
    end
  end

  test do
    system "#{bin}/ize"
  end
end
