# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "0.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kobrikx/test/releases/download/0.0.0/ize_0.0.0_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c6489f8dc585e97c54ee777a62edeffb0e469abe2b57c73c8e2001b8ef394a4a"

      def install
        bin.install "ize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kobrikx/test/releases/download/0.0.0/ize_0.0.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "fde113597137b5e392a4721a26424b73a4f34fd20b6a4f8427e2ac98c69ebb17"

      def install
        bin.install "ize"
      end
    end
  end

  test do
    system "#{bin}/ize"
  end
end
