# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "0.0.7"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kobrikx/test/releases/download/0.0.7/ize_0.0.7_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "19efdb836ed4fc5126419152b7384fed88a0021bf398ce17c4be3283536a4a19"

      def install
        bin.install "bin/ize"
      end
    end
  end

  test do
    system "#{bin}/ize"
  end
end
