name: "k6 github action k6 cloud test"

env:
    AWS_REGION: us-east-1

on:
  workflow_dispatch:
    inputs:
      API_URL:
        type: string
        required: true
        default: 'test.k6.io'
        description: 'Please input URL to test'
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ./apps/squibby/perftest/squibby-perftest.js
          flags: --env API_URL=${{ github.event.inputs.API_URL }}
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
