name: "k6 github action k6 local test"

on:
  workflow_dispatch:
    inputs:
      API_URL:
        type: string
        required: true
        default: 'test.k6.io'
        description: 'Please input URL to test'
      VIRTUAL_USERS:
        type: number
        required: true
        default: 5
        description: 'Please input amount of Virtual Users to test'
      DURATION:
        type: string
        required: true
        default: '60s'
        description: 'Please input time of testing'
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ./apps/squibby/perftest/squibby-perftest-summary.js
          flags: --vus ${{ github.event.inputs.VIRTUAL_USERS }} --duration ${{ github.event.inputs.DURATION }} --out json=summary.json
        env:
          API_URL: ${{ github.event.inputs.API_URL }}

      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: summary.json
