name: "Test2 tests2"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  ENV: ${{ github.event.inputs.env }}
  API_URL: https://38dc-35-180-56-28.ngrok-free.app/perftest
  EMAIL_RESULTS: "kobrikx@gmail.com"
  MINI_BOT_ID: "test"

on:
  workflow_dispatch:
    inputs:
      DRIVER_HUB:
        type: choice
        options:
          - https://${module.selenium_hub.r53_lb_dns_name}:4444
          - https://${module.selenium_hub.r53_lb_dns_name}:4444
          - https://${module.selenium_hub.r53_lb_dns_name}:4444
          - https://${module.selenium_hub.r53_lb_dns_name}:4444
        required: true
        default: 'https://${module.selenium_hub.r53_lb_dns_name}:4444'
        description: 'Please choose region'

jobs:
  bot_test:
    name: "Bot Test"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        amount: [ 50, 100, 200, 300 ]
    steps:
      - name: "Test ${{ matrix.amount }}"
        id: bot
        uses: indiesdev/curl@v1.1
        with:
          # The target URL
          # Required: true if custom-config is not set
          url: ${{ env.API_URL }}

          # The request method, basically it's one of GET|POST|PUT|PATCH
          # Default is GET
          method: "POST"

          # List of response status codes to be accepted, else it will set the job to be failed
          # If more than one value is needed, you can use comma (,) as separator
          # In this case if the response status code is not one of 200, 201 and 204, the job will be failed
          # Default is 200,201,204
          accept: 200,201,204


          headers: '{ "Content-Type": "application/json" }'

          # Body request
          # Apply only to POST|PUT request
          body: '{"count":${{ matrix.amount }},"emailResults":"${{ env.EMAIL_RESULTS }}","driverHub":"${{ github.event.inputs.DRIVER_HUB }}","miniBotID":"${{ env.MINI_BOT_ID }}"}'

          # Request timeout (millisec)
          # Default: 1000
          timeout: 10000

          # The authentication using token
          # This will override the Authorization header, for example Authorization: Bearer QWxhZGRpbjpPcGVuU2VzYW1l
          bearer-token: ${{ secrets.bearer_token }}


          # If it is set to true, it will show the response log in the GitHub UI
          # Default: false
          log-response: true

          # The number of attempts before giving up
          # Default: 1
          retries: 1

      - name: "Use response"
        continue-on-error: true
        run: echo ${{ steps.bot.outputs.response }}
