name: "[dev] Deploy Infra and Apps"
defaults:
  run:
    shell: bash

env:
  AWS_REGION: us-east-1
  ENV: dev
#  SSH_PUBLIC_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZqPTy/u82UzDtTY8GUdtGBrQQ1HoyMxZcv/Sc2FeSJTrcLh3i/Mo8pf/MrTO3G7LxJ8syDrptRFIVUheVY7a38UQvay94rJdYtSy6Z/0wLQbnDhJdhzzaPwXrUpBkZO7pcx2HNaC68D/40gTLEHVygJ09VEx8WS7d5QdS8YI6SnXF8ocLF6Nv1WV73aE8Cvz4aUgJJos7pvyX+/WoGzEwpj1aKVPOswRixf18Eg0G6H6WWDfK6zgqEUxsiiP7TB+yXp6VtbDRoS881PK7Cj3+X+lxMBAAuG/PslM6B6koiulCNWyauBZAuay3WR74dYWblYOpD54x1fzrELe2Q4v/1zTi669VqpVfPlH1cnpYiOXaP1aijCA9GFO/dWjxyAAkw2BVeEcbcDaIWhCToMYTHeq2f8Zzi9pxhZyJVO9qg4bXN3EeDGYrbFiWLdWxF9ITKmoSUYG5v8XhXzVTbAyBzDosDiBaa1pMsqFydgc4uZkKAF9govNw1KhRitovz9s= dev-nutcorp"
#  NAMESPACE: nutcorp
#  AWS_PROFILE: nutcorp-dev
#  IZE_LOG_LEVEL: debug
#  IZE_PLAIN_TEXT: true
#  IZE_VERSION: 1.1.12

on:
  workflow_dispatch:

jobs:
  infra:
    name: infra
    runs-on: ubuntu-latest
    env:
      TAG: "${{ github.sha }}"
    timeout-minutes: 60

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_PUBLIC_KEY }}
          name: id_rsa.pub
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Ize Setup
        uses: hazelops/action-setup-ize@1.0.1
        with:
          version: ${{ env.IZE_VERSION }}

      - name: Create AWS Profile
        run: ize gen aws-profile

      - name: Deploy Infra
        run: |
          ize version
          ize up infra

  squibby:
    name: squibby
    runs-on: ubuntu-latest
    env:
      TAG: "${{ github.sha }}"
    needs: infra
    timeout-minutes: 60

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_PUBLIC_KEY }}
          name: id_rsa.pub
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Ize Setup
        uses: hazelops/action-setup-ize@1.0.1
        with:
          version: ${{ env.IZE_VERSION }}

      - name: Create AWS Profile
        run: ize gen aws-profile

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build App
        run: ize up ${{ github.job }}

  goblin:
    name: goblin
    runs-on: ubuntu-latest
    env:
      TAG: "${{ github.sha }}"
    needs: infra
    timeout-minutes: 60

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_PUBLIC_KEY }}
          name: id_rsa.pub
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Ize Setup
        uses: hazelops/action-setup-ize@1.0.1
        with:
          version: ${{ env.IZE_VERSION }}

      - name: Create AWS Profile
        run: ize gen aws-profile

      - name: Deploy App
        run: ize up ${{ github.job }}
