name: "[dev02] Infra & Apps Deploy"
concurrency: # This is needed to ensure only a single job or workflow using the same concurrency group will run at a time.
  group: ${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  AWS_REGION: us-east-2
  ENV: dev02
  SSH_PUBLIC_KEY: "ssh-rsa 12345"
  AWS_PROFILE: default
  IZE_LOG_LEVEL: debug
  IZE_PLAIN_TEXT: true
  IZE_VERSION: 1.1.12
  NODE_OPTIONS: --max_old_space_size=6144
#  IBM_REPLICA_DB_SNAPSHOT_ID: ${{ github.event.inputs.ibm_replica_db_snapshot_id }}
#  RDS_API_DB_SNAPSHOT_ID: ${{ github.event.inputs.rds_api_db_snapshot_id }}
on:
  workflow_dispatch:
#    inputs:
#      ibm_replica_db_snapshot_id:
#        type: string
#        required: true
#        default: 'null'
#        description: 'IBM_REPLICA DB snapshot ID if it is necessary to restore (WILL OVERWRITE CURRENT DB)'
#      rds_api_db_snapshot_id:
#        type: string
#        required: true
#        default: 'null'
#        description: 'RDS_API DB snapshot ID if it is necessary to restore (WILL OVERWRITE CURRENT DB)'

  build-node_modules-lambda-layer:
    name: test upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: create test files
        run: |
          mkdir testfiles
          cd testfiles
          touch test1.txt
          touch test2.txt
          touch test3.txt
          touch test4.txt
          touch test5.txt
          ls -la ./testfiles
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: testfiles
          overwrite: true


  test-download:
    runs-on: ubuntu-latest
    name: test download
    env:
      TAG: '${{ github.sha }}'
    needs: [test upload]
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/download-artifact@v4
        with:
          name: test
          path: ./testfiles2

      - name: check what's downloaded
        run: |
          cd testfiles2
          ls -la ./
